#服务器配置
server:
  port: 8080
  servlet:
    context-path: /zyc

#数据库相关配置:
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/tb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: crh8612812
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  #解析resources/静态资源
  mvc:
    static-path-pattern: /**

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

  typeAliasesPackage: com.shop.zycshop.entity

global-config:

 id-type: 0

 logic-delete-value: 1

 logic-not-delete-value: 0

configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  cache-enabled: true

